import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Title in browswer tab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          yes I got that already. oh has a hot relaod nice... now lets just see about SCSS maybe later.

        </p>
        <p>
          I have got to figure out how to comment  in this structure
          {/* oh yeeeeeeeeeah  its JS inside this return to dom part so we have to use {} to place code in */}
          figure it out..  leave this here until a login is create. 
          <h2> Probably later want to put in a navbar above and a log in  modal  bootstrap maybe? to handle modal?</h2>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
